'use strict';
const $ = id => document.getElementById(id);
const decks = [
 {id:'warm',stars:1,style:'hollow',symbol:'☆',name:'暖身破冰',short:'暖身',en:'Break The Ice',color:'#ecda92',ink:'#263147',hint:'深呼吸，把第一句話交給卡牌。'},
 {id:'one',stars:1,style:'solid',symbol:'★',name:'一星連結',short:'一星',en:'One-Star Connection',color:'#eaa24e',ink:'#263147',hint:'從生活的小事，發現彼此的模樣。'},
 {id:'two',stars:2,style:'solid',symbol:'★★',name:'二星連結',short:'二星',en:'Two-Star Connection',color:'#c76b52',ink:'#fff4b3',hint:'多一點好奇，靠近真實的彼此。'},
 {id:'three',stars:3,style:'solid',symbol:'★★★',name:'三星連結',short:'三星',en:'Three-Star Connection',color:'#44888f',ink:'#f6ef87',hint:'慢慢說，也好好聽。'},
 {id:'four',stars:4,style:'solid',symbol:'★★★★',name:'離開之前的片刻',short:'四星',en:'Moments Before Goodbye',color:'#4d5c82',ink:'#f4ef66',hint:'離開之前，把這一刻留在心裡。'}
];
const KEY='mtw-deep-talk-v1';
let cards=[],selected='warm',busy=false,states={},ready=false;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const deck=()=>decks.find(d=>d.id===selected);
const pool=d=>cards.filter(c=>c.stars===d.stars&&c.star_style===d.style);
const state=()=>states[selected];
function persist(){try{localStorage.setItem(KEY,JSON.stringify({selected,states}));}catch{ $('draw-hint').textContent='目前無法儲存進度；關閉頁面後會重新開始。'; }}
function restore(){let saved;try{saved=JSON.parse(localStorage.getItem(KEY));}catch{};for(const d of decks){const valid=new Set(pool(d).map(c=>c.id));const history=[...new Set((Array.isArray(saved?.states?.[d.id]?.history)?saved.states[d.id].history:[]).filter(id=>valid.has(id)))];let cursor=saved?.states?.[d.id]?.cursor;states[d.id]={history,cursor:Number.isInteger(cursor)?Math.max(-1,Math.min(cursor,history.length-1)):history.length-1};}if(decks.some(d=>d.id===saved?.selected))selected=saved.selected;}
function buildDecks(){const nav=$('decks');for(const d of decks){const button=document.createElement('button');button.type='button';button.className='deck-option';button.dataset.deck=d.id;button.style.setProperty('--deck-color',d.color);button.innerHTML=`<span class="deck-swatch" style="background:${d.color};color:${d.ink}">${d.symbol}</span><span class="deck-text"><span class="deck-full">${d.name}</span><span class="deck-short">${d.short}</span><span class="deck-sub">${d.en}</span></span><span class="deck-count">${pool(d).length} 張</span>`;button.addEventListener('click',()=>selectDeck(d.id));nav.append(button);}}
function render(){const d=deck(),s=state(),all=pool(d);document.documentElement.style.setProperty('--accent',d.color);document.documentElement.style.setProperty('--ink',d.ink);$('deck-name').textContent=d.name;$('progress').textContent=`已抽 ${s.history.length} / ${all.length}`;$('progress-fill').style.width=`${s.history.length/all.length*100}%`;$('back-zh').textContent=d.name;$('back-en').textContent=d.en;document.querySelector('.back-stars').textContent=d.symbol;$('front-stars').textContent=d.symbol;for(const b of $('decks').children){b.setAttribute('aria-pressed',String(b.dataset.deck===selected));b.disabled=busy;}
 const card=cards.find(c=>c.id===s.history[s.cursor]);$('card-turn').classList.toggle('flipped',!!card);$('card-front').setAttribute('aria-hidden',String(!card));$('card-back').setAttribute('aria-hidden',String(!!card));if(card){$('question').textContent=card.text_zh;$('english-title').textContent=card.title_en;$('english-text').textContent=card.text_en;$('translation-note').hidden=!card.review_notes;$('card-number').textContent=`${String(s.cursor+1).padStart(2,'0')} / ${String(all.length).padStart(2,'0')}`;$('front-category').textContent=d.name;$('front-category-en').textContent=d.en;}
 $('previous').disabled=busy||s.cursor<=0;const forward=s.cursor<s.history.length-1;const exhausted=s.history.length===all.length&&!forward;$('draw').disabled=busy||exhausted;$('draw-label').textContent=busy?'讓緣分選一張…':exhausted?'這個牌組聊完了':forward?'回到下一張':card?'再抽一張':'抽一張卡';$('draw-hint').textContent=exhausted?'謝謝每一份分享。換個牌組，或重新洗牌。':d.hint;$('reset').disabled=busy;}
function selectDeck(id){if(!ready||busy||!decks.some(d=>d.id===id))return {ok:false,error:'牌組不存在或正在抽卡'};selected=id;render();persist();return {ok:true,deck:id};}
async function drawCard(){if(!ready||busy)return {ok:false,error:'尚未準備好'};const s=state(),remaining=pool(deck()).filter(c=>!s.history.includes(c.id));if(s.cursor>=s.history.length-1&&!remaining.length)return {ok:false,error:'牌組已抽完'};busy=true;render();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;$('card-turn').classList.remove('flipped');if(!reduced)await pause(350);$('stack').classList.add('shuffling');if(!reduced)await pause(480);$('stack').classList.remove('shuffling');if(s.cursor<s.history.length-1)s.cursor++;else{const array=new Uint32Array(1);crypto.getRandomValues(array);const next=remaining[Math.floor(array[0]/4294967296*remaining.length)];s.history.push(next.id);s.cursor=s.history.length-1;}busy=false;render();persist();const c=cards.find(c=>c.id===s.history[s.cursor]);$('announcement').textContent=`${deck().name}。${c.text_zh}`;return {ok:true,card:{id:c.id,text:c.text_zh}};}
$('draw').addEventListener('click',drawCard);$('previous').addEventListener('click',()=>{if(!busy&&state().cursor>0){state().cursor--;render();persist();$('announcement').textContent=$('question').textContent;}});$('help').addEventListener('click',()=>$('help-dialog').showModal());$('reset').addEventListener('click',()=>{if(!ready)return;$('reset-description').textContent=`「${deck().name}」已抽過的卡片會放回牌堆，其他牌組的進度會保留。`;$('reset-dialog').showModal();});$('cancel-reset').addEventListener('click',()=>$('reset-dialog').close());$('confirm-reset').addEventListener('click',()=>{states[selected]={history:[],cursor:-1};$('reset-dialog').close();render();persist();$('draw').focus();$('announcement').textContent='已重新洗牌。';});
async function init(){try{const response=await fetch('cards.json?v=4');if(!response.ok)throw new Error('cards unavailable');cards=await response.json();if(!Array.isArray(cards)||cards.length!==80||new Set(cards.map(c=>c.id)).size!==cards.length)throw new Error('invalid deck');restore();buildDecks();ready=true;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
 if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'get_deck_status',description:'查看此裝置的牌組與已抽張數',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('此操作不接受參數');return {selected,decks:decks.map(d=>({id:d.id,name:d.name,total:pool(d).length,drawn:states[d.id].history.length}))};}});}catch{}}
 }catch{ $('draw-label').textContent='牌組載入失敗';$('error').hidden=false;$('error').textContent='請確認網路連線後重試。';const retry=document.createElement('button');retry.className='text-button';retry.textContent='重新載入';retry.addEventListener('click',()=>location.reload());$('error').append(retry);}}
init();
